/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.actionrule;

import java.util.HashMap;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author rojatkaraditi
 */
public class ActionRuleUI extends javax.swing.JFrame {

    /**
     * Creates new form ActionRuleUI
     */
    public ActionRuleUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataFileButton = new javax.swing.JButton();
        AttributeFileButton = new javax.swing.JButton();
        dataFileLabel = new javax.swing.JLabel();
        attributeFileLabel = new javax.swing.JLabel();
        loadDataButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        delimeterBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minSupportText = new javax.swing.JTextField();
        minConfidenceText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loadedAttributes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        decisionAttributeBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        daFromBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        daToBox = new javax.swing.JComboBox<>();
        getReaminingAttrsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stableAttributeSelectList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        generateActionRulesButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        stableAttributesLabel = new javax.swing.JLabel();
        resultPane = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTextPane = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataFileButton.setText("Choose Data File");
        dataFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFileButtonActionPerformed(evt);
            }
        });

        AttributeFileButton.setText("Choose Attribute File");
        AttributeFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttributeFileButtonActionPerformed(evt);
            }
        });

        dataFileLabel.setText("no file selected");

        attributeFileLabel.setText("no file selected");

        loadDataButton.setText("Load Data");
        loadDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Delimeter: ");

        delimeterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ",","tab" }));
        delimeterBox.setSelectedIndex(0);
        delimeterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delimeterBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Minimum Support: ");

        jLabel3.setText("Minimum Confidence (%): ");

        minConfidenceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minConfidenceTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Attributes Loaded: ");

        loadedAttributes.setText("no attributes loaded yet.");

        jLabel6.setText("Decision Attribute: ");

        decisionAttributeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        decisionAttributeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisionAttributeBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Decision Value");

        jLabel8.setText("From:");

        daFromBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel9.setText("To:");

        daToBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        getReaminingAttrsButton.setText("Get Remaining Attributes");
        getReaminingAttrsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getReaminingAttrsButtonActionPerformed(evt);
            }
        });

        stableAttributeSelectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        stableAttributeSelectList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                stableAttributeSelectListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(stableAttributeSelectList);

        jLabel5.setText("Select Stable Attributes:");

        generateActionRulesButton.setText("Get Action Rules");
        generateActionRulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionRulesButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Selected Stable Attributes:");

        stableAttributesLabel.setText("no attributes selected");

        resultTextPane.setColumns(20);
        resultTextPane.setRows(5);
        jScrollPane2.setViewportView(resultTextPane);

        resultPane.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(delimeterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel4))
                                                .addGap(61, 61, 61))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(loadedAttributes)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(minSupportText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(minConfidenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(decisionAttributeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(daFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(daToBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(152, 152, 152)
                                                .addComponent(generateActionRulesButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(131, 131, 131)
                                                .addComponent(stableAttributesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(119, 119, 119)
                                        .addComponent(jLabel11))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataFileButton)
                                    .addComponent(AttributeFileButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attributeFileLabel)
                                    .addComponent(dataFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(loadDataButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(getReaminingAttrsButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataFileButton)
                    .addComponent(dataFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttributeFileButton)
                    .addComponent(attributeFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(delimeterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadDataButton)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loadedAttributes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minSupportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(decisionAttributeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minConfidenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(daFromBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(daToBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(getReaminingAttrsButton)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stableAttributesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateActionRulesButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFileButtonActionPerformed
        // TODO add your handling code here:
                JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
		
		      FileNameExtensionFilter filter = new FileNameExtensionFilter("txt files","txt");
		fileChooser.setFileFilter(filter);
		
		int val = fileChooser.showOpenDialog(null); 
		
        if (val == JFileChooser.APPROVE_OPTION) {
            dataFileLabel.setText(fileChooser.getSelectedFile().getAbsolutePath()); 
        } 
    }//GEN-LAST:event_dataFileButtonActionPerformed

    private void AttributeFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttributeFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 
		
		FileNameExtensionFilter filter = new FileNameExtensionFilter("txt files","txt");
		fileChooser.setFileFilter(filter);
		
		int val = fileChooser.showOpenDialog(null); 
		
        if (val == JFileChooser.APPROVE_OPTION) {
            attributeFileLabel.setText(fileChooser.getSelectedFile().getAbsolutePath()); 
        } 
    }//GEN-LAST:event_AttributeFileButtonActionPerformed

    private void delimeterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delimeterBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delimeterBoxActionPerformed

    private void minConfidenceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minConfidenceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minConfidenceTextActionPerformed

    private void getReaminingAttrsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getReaminingAttrsButtonActionPerformed
        // TODO add your handling code here:
        try{
            fr.setMinConfidence(Double.parseDouble(minConfidenceText.getText()));
            fr.setMinSupport(Integer.parseInt(minSupportText.getText()));
            HashMap<String,Set<String>> attributes = fr.getAttributes();
            String decisionAttribute = decisionAttributeBox.getSelectedItem().toString();
            attributes.remove(decisionAttribute);
            //String [] arr = new String [attributes.size()];

           stableAttributeSelectList.setListData(attributes.keySet().toArray(new String[attributes.size()]));
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_getReaminingAttrsButtonActionPerformed

    private void generateActionRulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionRulesButtonActionPerformed
        // TODO add your handling code here:
        fr.setStableAttributes(stableAttributeSelectList.getSelectedValuesList());
        resultTextPane.setText(fr.toString()+"\n"+fr.toString()+"\n"+fr.toString()+"\n"+fr.toString()+"\n"+fr.toString()+"\n"+fr.toString()+"\n"+fr.toString());
    }//GEN-LAST:event_generateActionRulesButtonActionPerformed

    private void loadDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataButtonActionPerformed
        // TODO add your handling code here:
        fr.setAttributeFile(attributeFileLabel.getText());
    	fr.setDataFile(dataFileLabel.getText());
    	fr.setDelimeter(delimeterBox.getSelectedItem().toString());
        
        HashMap<String,Set<String>> attributes = fr.getAttributes();
        loadedAttributes.setText(attributes.keySet().toString());
        
        decisionAttributeBox.removeAllItems();
        
        for(String attribute:attributes.keySet()){
            decisionAttributeBox.addItem(attribute);
        }
        
    }//GEN-LAST:event_loadDataButtonActionPerformed

    private void decisionAttributeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisionAttributeBoxActionPerformed
        // TODO add your handling code here:
        HashMap<String,Set<String>> attributes = fr.getAttributes();
        
        if(decisionAttributeBox!=null && decisionAttributeBox.getSelectedItem()!=null){
            String selectedAttribute = decisionAttributeBox.getSelectedItem().toString();
            Set<String> attrValues= attributes.get(selectedAttribute);
            daFromBox.removeAllItems();
            daToBox.removeAllItems();
            for(String value:attrValues){
                daFromBox.addItem(value);
                daToBox.addItem(value);
            }
            daFromBox.setSelectedIndex(0);
            daToBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_decisionAttributeBoxActionPerformed

    private void stableAttributeSelectListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_stableAttributeSelectListValueChanged
        // TODO add your handling code here:
        //System.out.println(stableAttributeSelectList.getSelectedValuesList());
        stableAttributesLabel.setText(stableAttributeSelectList.getSelectedValuesList().toString());
    }//GEN-LAST:event_stableAttributeSelectListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActionRuleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActionRuleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActionRuleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActionRuleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActionRuleUI().setVisible(true);
            }
        });
    }
    
    FileReader fr = new FileReader();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttributeFileButton;
    private javax.swing.JLabel attributeFileLabel;
    private javax.swing.JComboBox<String> daFromBox;
    private javax.swing.JComboBox<String> daToBox;
    private javax.swing.JButton dataFileButton;
    private javax.swing.JLabel dataFileLabel;
    private javax.swing.JComboBox<String> decisionAttributeBox;
    private javax.swing.JComboBox<String> delimeterBox;
    private javax.swing.JButton generateActionRulesButton;
    private javax.swing.JButton getReaminingAttrsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadDataButton;
    private javax.swing.JLabel loadedAttributes;
    private javax.swing.JTextField minConfidenceText;
    private javax.swing.JTextField minSupportText;
    private java.awt.ScrollPane resultPane;
    private javax.swing.JTextArea resultTextPane;
    private javax.swing.JList<String> stableAttributeSelectList;
    private javax.swing.JLabel stableAttributesLabel;
    // End of variables declaration//GEN-END:variables
}
